import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {Store as SQLiteStore} from '../../src/database.js';
import {Worker} from '../../src/worker.js';
import {config} from '../../src/config.js';
import {normalizeSignal} from '../../src/domain.js';
import {encryptJson} from '../../src/security.js';
import {PostgresDatabase} from '../../src/postgres/db.js';
import {Store} from '../../src/postgres/store.js';
import {importSqlite} from '../../scripts/import-postgres.mjs';

test('schema 10 import backs up, preserves credentials and ledger, revokes sessions, and refuses nonempty target',async t=>{
  assert.ok(process.env.TEST_DATABASE_URL,'Real PostgreSQL is required');
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'robot-phase2-import-')),source=path.join(dir,'source.db');
  const old=new SQLiteStore(source),user=old.createUser({email:'fixture@example.test',passwordHash:'fixture-hash',role:'ADMIN'});
  old.setRisk(user.id,{...config.defaultRisk,blockHighVolatility:false,blockDuringNews:false,equities:{'binance-global':10},balances:{'binance-global':10}});
  const encrypted=encryptJson({secret:'fixture-webhook'},config.keyring,'webhook:'+user.id);old.setWebhookSecret(user.id,'fixture-webhook',encrypted);
  old.createSession(user.id,'old-session',Date.now()+60000);
  old.enqueue(user.id,normalizeSignal({trade_id:'old-fill',broker:'Binance Global',symbol:'BTCUSD',event:'BUY',entry:0.1,sl:0.09,quantity:1,timestamp:Date.now()}));
  await new Worker({store:old,config}).tick();old.db.prepare('UPDATE signals SET slippage_bps=?').run(1e-20);old.close();
  const digest=()=>createHash('sha256').update(fs.readFileSync(source)).digest('hex'),before=digest();
  const admin=new PostgresDatabase({connectionString:process.env.TEST_DATABASE_URL}),dbName='robot_phase2_import_'+randomUUID().replaceAll('-','');
  await admin.query('CREATE DATABASE '+dbName);const url=new URL(process.env.TEST_DATABASE_URL);url.pathname='/'+dbName;
  const db=new PostgresDatabase({connectionString:url.toString()});
  t.after(async()=>{await db.close();await admin.query('DROP DATABASE '+dbName);await admin.close();fs.rmSync(dir,{recursive:true,force:true});});
  await assert.rejects(importSqlite({source,backupPath:path.join(dir,'strict-backup.db'),db}),/Legacy REAL precision/);
  assert.equal((await db.prepare('SELECT count(*) n FROM users').get()).n,0);
  const result=await importSqlite({source,backupPath:path.join(dir,'backup.db'),db,roundLegacy:true});assert.equal(result.counts.fills,1);assert.equal(result.sessionsRevoked,1);assert.equal(digest(),before);
  assert.equal(result.rounding['signals.slippage_bps'].values,1);
  assert.equal((await db.prepare('SELECT count(*) n FROM sessions').get()).n,0);
  const store=new Store(db);assert.equal((await store.webhookSecret(user.id)).webhook_secret_encrypted,encrypted);
  assert.equal((await store.userByEmail('fixture@example.test')).password_hash,'fixture-hash');
  assert.equal((await store.paperAccount(user.id,'binance-global')).cash,'9.9');
  assert.equal((await store.listSignals(user.id))[0].trade_id,'old-fill');
  await assert.rejects(importSqlite({source,backupPath:path.join(dir,'second.db'),db}),/Target must be empty/);
  assert.equal((await db.prepare('SELECT count(*) n FROM fills').get()).n,1);
});
