-- PostgreSQL baseline for Phase 2. Monetary values are exact NUMERIC.
CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'USER',status TEXT NOT NULL DEFAULT 'ACTIVE',webhook_secret_hash TEXT UNIQUE,webhook_hint TEXT,created_at BIGINT NOT NULL, webhook_secret_encrypted TEXT, parent_user_id TEXT REFERENCES users(id), bot_slot_index BIGINT NOT NULL DEFAULT 1 CHECK(bot_slot_index BETWEEN 1 AND 5), label TEXT NOT NULL DEFAULT 'Main Bot');

CREATE TABLE licenses(id TEXT PRIMARY KEY,key_hash TEXT NOT NULL UNIQUE,key_hint TEXT NOT NULL,plan TEXT NOT NULL,status TEXT NOT NULL,expires_at BIGINT NOT NULL,assigned_user_id TEXT,created_at BIGINT NOT NULL,FOREIGN KEY(assigned_user_id) REFERENCES users(id));

CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at BIGINT NOT NULL,created_at BIGINT NOT NULL, last_seen BIGINT NOT NULL DEFAULT 0, elevated_until BIGINT NOT NULL DEFAULT 0, mfa_verified BIGINT NOT NULL DEFAULT 0,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE broker_credentials(user_id TEXT NOT NULL,broker TEXT NOT NULL,encrypted_data TEXT NOT NULL,enabled BIGINT NOT NULL DEFAULT 1,updated_at BIGINT NOT NULL,PRIMARY KEY(user_id,broker),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE risk_profiles(user_id TEXT PRIMARY KEY,policy TEXT NOT NULL,updated_at BIGINT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE signals(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id TEXT NOT NULL,trade_id TEXT NOT NULL,received_at BIGINT NOT NULL,signal_time BIGINT NOT NULL,broker TEXT NOT NULL,symbol TEXT NOT NULL,timeframe TEXT,event TEXT NOT NULL,side TEXT NOT NULL,entry_price NUMERIC(38,18),stop_loss NUMERIC(38,18),take_profit NUMERIC(38,18),payload TEXT NOT NULL,status TEXT NOT NULL,error_message TEXT,broker_response TEXT,order_id TEXT,fill_price NUMERIC(38,18),slippage_bps NUMERIC(38,18),applied_quantity NUMERIC(38,18) NOT NULL DEFAULT 0,applied_quote NUMERIC(38,18) NOT NULL DEFAULT 0,processed_at BIGINT, execution_mode TEXT NOT NULL DEFAULT 'LEGACY', account_id TEXT NOT NULL DEFAULT 'legacy', client_order_id TEXT, order_intent TEXT, checked_at BIGINT NOT NULL DEFAULT 0, review_note TEXT NOT NULL DEFAULT '',UNIQUE(user_id,trade_id),FOREIGN KEY(user_id) REFERENCES users(id));

CREATE TABLE audit(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id TEXT,ts BIGINT NOT NULL,event TEXT NOT NULL,trade_id TEXT,details TEXT NOT NULL);

CREATE TABLE positions(user_id TEXT NOT NULL,broker TEXT NOT NULL,symbol TEXT NOT NULL,quantity NUMERIC(38,18) NOT NULL DEFAULT 0,avg_price NUMERIC(38,18) NOT NULL DEFAULT 0,stop_loss NUMERIC(38,18),take_profit NUMERIC(38,18),updated_at BIGINT NOT NULL,PRIMARY KEY(user_id,broker,symbol));

CREATE TABLE daily_stats(user_id TEXT NOT NULL,day TEXT NOT NULL,trades BIGINT NOT NULL DEFAULT 0,notional NUMERIC(38,18) NOT NULL DEFAULT 0,realized_r NUMERIC(38,18) NOT NULL DEFAULT 0,loss_streak BIGINT NOT NULL DEFAULT 0,PRIMARY KEY(user_id,day));

CREATE TABLE system_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);

CREATE TABLE ledger_positions(
  user_id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  execution_mode TEXT NOT NULL,
  broker TEXT NOT NULL,
  symbol TEXT NOT NULL,
  quantity NUMERIC(38,18) NOT NULL DEFAULT 0,
  avg_price NUMERIC(38,18) NOT NULL DEFAULT 0,
  stop_loss NUMERIC(38,18),
  take_profit NUMERIC(38,18),
  initial_risk NUMERIC(38,18) NOT NULL DEFAULT 0,
  cumulative_pnl NUMERIC(38,18) NOT NULL DEFAULT 0,
  updated_at BIGINT NOT NULL,
  cost_basis NUMERIC(38,18) NOT NULL DEFAULT 0,
  PRIMARY KEY(user_id,account_id,execution_mode,symbol)
);

CREATE TABLE ledger_daily(
  user_id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  execution_mode TEXT NOT NULL,
  day TEXT NOT NULL,
  trades BIGINT NOT NULL DEFAULT 0,
  notional NUMERIC(38,18) NOT NULL DEFAULT 0,
  realized_r NUMERIC(38,18) NOT NULL DEFAULT 0,
  PRIMARY KEY(user_id,account_id,execution_mode,day)
);

CREATE TABLE ledger_streak(
  user_id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  execution_mode TEXT NOT NULL,
  loss_streak BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY(user_id,account_id,execution_mode)
);

CREATE TABLE fills(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_id BIGINT NOT NULL REFERENCES signals(id) ON DELETE CASCADE,
  received_at BIGINT NOT NULL,
  source TEXT NOT NULL,
  side TEXT NOT NULL,
  price NUMERIC(38,18) NOT NULL,
  delta_quantity NUMERIC(38,18) NOT NULL,
  cumulative_quantity NUMERIC(38,18) NOT NULL,
  quote_amount NUMERIC(38,18) NOT NULL DEFAULT 0,
  fee_quote NUMERIC(38,18) NOT NULL DEFAULT 0,
  legacy_float BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ledger_position_allocations(
  position_id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  execution_mode TEXT NOT NULL,
  broker TEXT NOT NULL,
  symbol TEXT NOT NULL,
  entry_signal_id BIGINT NOT NULL REFERENCES signals(id),
  entry_trade_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'OPEN',
  filled_quantity NUMERIC(38,18) NOT NULL,
  remaining_quantity NUMERIC(38,18) NOT NULL,
  reserved_quantity NUMERIC(38,18) NOT NULL DEFAULT 0,
  entry_price NUMERIC(38,18) NOT NULL,
  stop_loss NUMERIC(38,18),
  take_profit NUMERIC(38,18),
  opened_at BIGINT NOT NULL,
  closed_at BIGINT,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_allocations_open ON ledger_position_allocations(user_id,account_id,execution_mode,symbol,status);

CREATE TABLE schema_version(version INTEGER PRIMARY KEY);
INSERT INTO schema_version VALUES(12);