-- PostgreSQL baseline for Phase 2. Monetary values are exact NUMERIC.
CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'USER',status TEXT NOT NULL DEFAULT 'ACTIVE',webhook_secret_hash TEXT UNIQUE,webhook_hint TEXT,created_at BIGINT NOT NULL, webhook_secret_encrypted TEXT, parent_user_id TEXT REFERENCES users(id), bot_slot_index BIGINT NOT NULL DEFAULT 1 CHECK(bot_slot_index BETWEEN 1 AND 5), label TEXT NOT NULL DEFAULT 'Main Bot');

CREATE TABLE licenses(id TEXT PRIMARY KEY,key_hash TEXT NOT NULL UNIQUE,key_hint TEXT NOT NULL,plan TEXT NOT NULL,status TEXT NOT NULL,expires_at BIGINT NOT NULL,assigned_user_id TEXT,created_at BIGINT NOT NULL,FOREIGN KEY(assigned_user_id) REFERENCES users(id));

CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at BIGINT NOT NULL,created_at BIGINT NOT NULL, last_seen BIGINT NOT NULL DEFAULT 0, elevated_until BIGINT NOT NULL DEFAULT 0, mfa_verified BIGINT NOT NULL DEFAULT 0,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE broker_credentials(user_id TEXT NOT NULL,broker TEXT NOT NULL,encrypted_data TEXT NOT NULL,enabled BIGINT NOT NULL DEFAULT 1,updated_at BIGINT NOT NULL,PRIMARY KEY(user_id,broker),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE risk_profiles(user_id TEXT PRIMARY KEY,policy TEXT NOT NULL,updated_at BIGINT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE signals(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id TEXT NOT NULL,trade_id TEXT NOT NULL,received_at BIGINT NOT NULL,signal_time BIGINT NOT NULL,broker TEXT NOT NULL,symbol TEXT NOT NULL,timeframe TEXT,event TEXT NOT NULL,side TEXT NOT NULL,entry_price NUMERIC(38,18),stop_loss NUMERIC(38,18),take_profit NUMERIC(38,18),payload TEXT NOT NULL,status TEXT NOT NULL,error_message TEXT,broker_response TEXT,order_id TEXT,fill_price NUMERIC(38,18),slippage_bps NUMERIC(38,18),applied_quantity NUMERIC(38,18) NOT NULL DEFAULT 0,applied_quote NUMERIC(38,18) NOT NULL DEFAULT 0,processed_at BIGINT, execution_mode TEXT NOT NULL DEFAULT 'LEGACY', account_id TEXT NOT NULL DEFAULT 'legacy', client_order_id TEXT, order_intent TEXT, checked_at BIGINT NOT NULL DEFAULT 0, review_note TEXT NOT NULL DEFAULT '',UNIQUE(user_id,trade_id),FOREIGN KEY(user_id) REFERENCES users(id));

CREATE TABLE audit(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id TEXT,ts BIGINT NOT NULL,event TEXT NOT NULL,trade_id TEXT,details TEXT NOT NULL);

CREATE TABLE positions(user_id TEXT NOT NULL,broker TEXT NOT NULL,symbol TEXT NOT NULL,quantity NUMERIC(38,18) NOT NULL DEFAULT 0,avg_price NUMERIC(38,18) NOT NULL DEFAULT 0,stop_loss NUMERIC(38,18),take_profit NUMERIC(38,18),updated_at BIGINT NOT NULL,PRIMARY KEY(user_id,broker,symbol));

CREATE TABLE daily_stats(user_id TEXT NOT NULL,day TEXT NOT NULL,trades BIGINT NOT NULL DEFAULT 0,notional NUMERIC(38,18) NOT NULL DEFAULT 0,realized_r NUMERIC(38,18) NOT NULL DEFAULT 0,loss_streak BIGINT NOT NULL DEFAULT 0,PRIMARY KEY(user_id,day));

CREATE TABLE system_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);

CREATE TABLE ledger_positions(
        user_id TEXT NOT NULL, account_id TEXT NOT NULL, execution_mode TEXT NOT NULL,
        broker TEXT NOT NULL, symbol TEXT NOT NULL, quantity NUMERIC(38,18) NOT NULL DEFAULT 0,
        avg_price NUMERIC(38,18) NOT NULL DEFAULT 0, stop_loss NUMERIC(38,18), take_profit NUMERIC(38,18),
        initial_risk NUMERIC(38,18) NOT NULL DEFAULT 0, cumulative_pnl NUMERIC(38,18) NOT NULL DEFAULT 0,
        updated_at BIGINT NOT NULL,
        PRIMARY KEY(user_id,account_id,execution_mode,symbol));

CREATE TABLE ledger_daily(
        user_id TEXT NOT NULL, account_id TEXT NOT NULL, execution_mode TEXT NOT NULL,
        day TEXT NOT NULL, trades BIGINT NOT NULL DEFAULT 0, notional NUMERIC(38,18) NOT NULL DEFAULT 0,
        realized_r NUMERIC(38,18) NOT NULL DEFAULT 0,
        PRIMARY KEY(user_id,account_id,execution_mode,day));

CREATE TABLE ledger_streak(
        user_id TEXT NOT NULL, account_id TEXT NOT NULL, execution_mode TEXT NOT NULL,
        loss_streak BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY(user_id,account_id,execution_mode));

CREATE TABLE fills(
        signal_id BIGINT NOT NULL, cumulative_quantity NUMERIC(38,18) NOT NULL,
        delta_quantity NUMERIC(38,18) NOT NULL, price NUMERIC(38,18) NOT NULL, fee_quote NUMERIC(38,18) NOT NULL,
        realized_r NUMERIC(38,18) NOT NULL, received_at BIGINT NOT NULL,
        PRIMARY KEY(signal_id,cumulative_quantity));

CREATE TABLE notification_outbox(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL,
        attempts BIGINT NOT NULL DEFAULT 0, next_attempt BIGINT NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'PENDING');

CREATE TABLE analytics_settings(
      user_id TEXT NOT NULL,broker TEXT NOT NULL,fee_bps NUMERIC(38,18) NOT NULL DEFAULT 0,updated_at BIGINT NOT NULL,
      PRIMARY KEY(user_id,broker),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE paper_funding(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), broker TEXT NOT NULL,
      at BIGINT NOT NULL, equity_delta NUMERIC(38,18) NOT NULL, cash_delta NUMERIC(38,18) NOT NULL,
      kind TEXT NOT NULL CHECK(kind IN ('CONFIGURATION','LEGACY_BASELINE')));

CREATE TABLE paper_cash_journal(
      signal_id BIGINT NOT NULL REFERENCES signals(id), cumulative_quantity NUMERIC(38,18) NOT NULL,
      user_id TEXT NOT NULL REFERENCES users(id), broker TEXT NOT NULL,
      cash_delta NUMERIC(38,18) NOT NULL, at BIGINT NOT NULL,
      PRIMARY KEY(signal_id,cumulative_quantity));

CREATE TABLE paper_snapshots(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), broker TEXT NOT NULL,
      at BIGINT NOT NULL, reason TEXT NOT NULL, cash NUMERIC(38,18) NOT NULL,
      book_equity NUMERIC(38,18) NOT NULL, position_cost NUMERIC(38,18) NOT NULL);

CREATE TABLE user_security(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
      mfa_secret TEXT,pending_secret TEXT,pending_expires BIGINT NOT NULL DEFAULT 0,last_step BIGINT NOT NULL DEFAULT -1);

CREATE TABLE mfa_recovery(user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,code_hash TEXT NOT NULL,
      PRIMARY KEY(user_id,code_hash));

CREATE TABLE auth_challenges(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at BIGINT NOT NULL,attempts BIGINT NOT NULL DEFAULT 0);

CREATE TABLE password_resets(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at BIGINT NOT NULL);

CREATE TABLE security_limits(key_hash TEXT PRIMARY KEY,attempts BIGINT NOT NULL,expires_at BIGINT NOT NULL);

CREATE TABLE security_mail(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      encrypted_body TEXT NOT NULL,expires_at BIGINT NOT NULL,attempts BIGINT NOT NULL DEFAULT 0,
      next_attempt BIGINT NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'PENDING');

CREATE INDEX idx_signals_queue ON signals(status,id);
CREATE INDEX idx_signals_user ON signals(user_id,id DESC);
CREATE UNIQUE INDEX idx_bot_slot ON users(COALESCE(parent_user_id,id),bot_slot_index);
CREATE INDEX idx_bot_parent ON users(parent_user_id);
CREATE INDEX idx_paper_funding_account ON paper_funding(user_id,broker,at,id);
CREATE INDEX idx_paper_cash_account ON paper_cash_journal(user_id,broker,at);
CREATE INDEX idx_paper_snapshots_account ON paper_snapshots(user_id,broker,at,id);
CREATE INDEX idx_reset_user ON password_resets(user_id);

ALTER TABLE ledger_positions ADD COLUMN cost_basis NUMERIC(38,18) NOT NULL DEFAULT 0;
ALTER TABLE ledger_positions ADD FOREIGN KEY(user_id) REFERENCES users(id);
ALTER TABLE ledger_positions ADD CHECK(quantity>=0 AND cost_basis>=0);
ALTER TABLE ledger_daily ADD FOREIGN KEY(user_id) REFERENCES users(id);
ALTER TABLE ledger_streak ADD FOREIGN KEY(user_id) REFERENCES users(id);
ALTER TABLE fills ADD FOREIGN KEY(signal_id) REFERENCES signals(id);
ALTER TABLE fills ADD CHECK(delta_quantity>0 AND cumulative_quantity>0 AND price>0 AND fee_quote>=0);
ALTER TABLE fills ADD quote_amount NUMERIC(38,18) CHECK(quote_amount>0);
ALTER TABLE fills ADD legacy_float BIGINT NOT NULL DEFAULT 0 CHECK(legacy_float IN (0,1));
ALTER TABLE notification_outbox ADD FOREIGN KEY(user_id) REFERENCES users(id);
ALTER TABLE notification_outbox ADD COLUMN lease_token TEXT;
ALTER TABLE notification_outbox ADD COLUMN lease_until BIGINT NOT NULL DEFAULT 0;
ALTER TABLE security_mail ADD COLUMN lease_token TEXT;
ALTER TABLE security_mail ADD COLUMN lease_until BIGINT NOT NULL DEFAULT 0;
CREATE TABLE schema_version(version INTEGER PRIMARY KEY);
INSERT INTO schema_version VALUES(11);
CREATE INDEX idx_execution_ready ON signals(id) WHERE status='QUEUED';
CREATE INDEX idx_pending_scope ON signals(user_id,account_id,execution_mode,status);
CREATE INDEX idx_outbox_ready ON notification_outbox(next_attempt,id) WHERE status='PENDING';
CREATE INDEX idx_security_mail_ready ON security_mail(next_attempt,id) WHERE status='PENDING';
CREATE TABLE worker_heartbeats(id TEXT PRIMARY KEY, last_tick BIGINT NOT NULL, role TEXT NOT NULL);
CREATE FUNCTION check_bot_parent() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.parent_user_id IS NOT NULL AND (NEW.bot_slot_index=1 OR NOT EXISTS(
 SELECT 1 FROM users WHERE id=NEW.parent_user_id AND parent_user_id IS NULL)) THEN
 RAISE EXCEPTION 'Invalid bot owner or slot';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER bot_parent_guard BEFORE INSERT OR UPDATE OF parent_user_id,bot_slot_index ON users
FOR EACH ROW EXECUTE FUNCTION check_bot_parent();
