import {evaluateRisk} from './risk.js';
import {decryptJson} from './security.js';
import {executeOrder,fetchOrderStatus} from './adapters/registry.js';

export class Worker{
  constructor({store,config,notifier}){Object.assign(this,{store,config,notifier});this.busy=false;this.lastReconcile=0;}
  start(){this.timer=setInterval(()=>this.tick(),this.config.workerIntervalMs);this.timer.unref();this.tick();}
  stop(){clearInterval(this.timer);}
  async tick(){if(this.busy)return;const job=this.store.claimNext();if(!job){if(Date.now()-this.lastReconcile>5000)await this.reconcile();return;}this.busy=true;const signal=job.payload;const user=this.store.userById(job.user_id);
    try{
      const policy=this.store.risk(job.user_id,this.config.defaultRisk),position=this.store.position(job.user_id,signal.broker,signal.symbol);
      const result=evaluateRisk(signal,{policy,daily:this.store.today(job.user_id),position,equity:policy.equities?.[signal.broker]||0,licensed:user?.role==='ADMIN'||this.store.hasActiveLicense(job.user_id),globalKill:this.store.getSetting('globalKill',false),openPositions:this.store.openPositionCount(job.user_id),hasPendingOrder:this.store.hasPendingOrder(job.user_id,signal.broker,signal.symbol)});
      if(!result.ok){this.store.complete(job.id,'REJECTED',{error:result.reason});this.store.audit(job.user_id,'risk.rejected',signal.tradeId,{reason:result.reason});void this.notifier.send(user?.email,`Astra rejected ${signal.tradeId}`,result.reason);return;}
      const order=result.order,paper=policy.paperTrading??this.config.paperTrading;let execution;
      if(paper)execution={status:'FILLED',orderId:`PAPER-${signal.tradeId}`,executedQty:order.quantity,quoteQty:order.notional,fillPrice:order.price,raw:{paper:true,status:'FILLED'}};
      else{const row=this.store.credential(job.user_id,signal.broker);if(!row)throw new Error('Broker credentials are not configured or enabled');execution=await executeOrder(signal.broker,decryptJson(row.encrypted_data,this.config.masterKey),order);}
      const fillPrice=execution.fillPrice||(execution.executedQty?execution.quoteQty/execution.executedQty:undefined);const slippageBps=fillPrice&&order.price?(signal.side==='BUY'?(fillPrice-order.price):(order.price-fillPrice))/order.price*10000:null;
      let realizedR=0,isClosed=false;if(execution.executedQty>0){({realizedR,isClosed}=this.applyFill(job.user_id,{...order,quantity:execution.executedQty,price:fillPrice||order.price,notional:execution.quoteQty||execution.executedQty*(fillPrice||order.price)}));}
      this.store.addDaily(job.user_id,order.notional,realizedR,isClosed);
      const status=paper?'FILLED':execution.status==='FILLED'?'FILLED':execution.status==='PARTIALLY_FILLED'?'PARTIALLY_FILLED':'SUBMITTED';
      this.store.complete(job.id,status,{response:execution.raw,orderId:execution.orderId,fillPrice:fillPrice||null,slippageBps,appliedQuantity:execution.executedQty||0,appliedQuote:execution.quoteQty||0});this.store.audit(job.user_id,'order.accepted',signal.tradeId,{paper,status,orderId:execution.orderId,fillPrice,slippageBps});
      void this.notifier.send(user?.email,`Astra ${status}: ${signal.symbol}`,`${signal.event} ${signal.symbol}\nTrade ID: ${signal.tradeId}\nOrder ID: ${execution.orderId||'-'}\nFill: ${fillPrice||'-'}\nSlippage: ${slippageBps??'-'} bps`);
    }catch(error){this.store.complete(job.id,'ERROR',{error:error.message});this.store.audit(job.user_id,'order.error',signal.tradeId,{message:error.message});void this.notifier.send(user?.email,`Astra error ${signal.tradeId}`,error.message);}finally{this.busy=false;}}
  async reconcile(){this.lastReconcile=Date.now();const row=this.store.nextPending();if(!row)return;this.busy=true;try{const credential=this.store.credential(row.user_id,row.broker);if(!credential)return;const execution=await fetchOrderStatus(row.broker,decryptJson(credential.encrypted_data,this.config.masterKey),row);if(!execution)return;const totalQty=Number(execution.executedQty||0),totalQuote=Number(execution.quoteQty||0),deltaQty=Math.max(0,totalQty-row.applied_quantity),deltaQuote=Math.max(0,totalQuote-row.applied_quote),fillPrice=execution.fillPrice||(totalQty&&totalQuote?totalQuote/totalQty:null),signal=row.payload;if(deltaQty>0){const result=this.applyFill(row.user_id,{...signal,quantity:deltaQty,price:deltaQuote&&deltaQty?deltaQuote/deltaQty:(fillPrice||signal.referencePrice),notional:deltaQuote||deltaQty*(fillPrice||signal.referencePrice)});if(result.isClosed)this.store.addRealized(row.user_id,result.realizedR);}const status=['FILLED','CANCELED','REJECTED','EXPIRED'].includes(execution.status)?execution.status:(totalQty>0?'PARTIALLY_FILLED':'SUBMITTED'),entry=row.entry_price,slippageBps=fillPrice&&entry?(signal.side==='BUY'?(fillPrice-entry):(entry-fillPrice))/entry*10000:null;this.store.updateExecution(row.id,status,{response:execution.raw,fillPrice,slippageBps,appliedQuantity:totalQty,appliedQuote:totalQuote});this.store.audit(row.user_id,'order.reconciled',row.trade_id,{status,fillPrice,totalQty});}catch(error){this.store.audit(row.user_id,'reconcile.error',row.trade_id,{message:error.message});}finally{this.busy=false;}}
  applyFill(userId,order){const current=this.store.position(userId,order.broker,order.symbol);if(order.side==='BUY'){const quantity=current.quantity+order.quantity,avg=((current.quantity*current.avg_price)+order.notional)/quantity;this.store.setPosition(userId,order.broker,order.symbol,quantity,avg,order.stopLoss,order.takeProfit);return{realizedR:0,isClosed:false};}
    const sold=Math.min(order.quantity,current.quantity),pnl=(order.price-current.avg_price)*sold,riskPerUnit=current.stop_loss?Math.abs(current.avg_price-current.stop_loss):0,realizedR=riskPerUnit?pnl/(riskPerUnit*sold):0,quantity=Math.max(0,current.quantity-sold);this.store.setPosition(userId,order.broker,order.symbol,quantity,quantity?current.avg_price:0,quantity?current.stop_loss:null,quantity?current.take_profit:null);return{realizedR,isClosed:sold>0};}
}
